spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: "true"
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.Oracle10gDialect"
        
  datasource:
    url: "jdbc:oracle:thin:@10.225.13.19:1521/motcred"
    username: "regularizacion"
    password: "regularizacion123"
    driver-class-name: "oracle.jdbc.OracleDriver"
        
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration
    
server:
  port: 8083